// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsj4AL-XM7624dmyBmTLKUqpsZTzUd9Kg',
    appId: '1:93120238692:web:e66c4ad2629ca362a4bb71',
    messagingSenderId: '93120238692',
    projectId: 'task-app-1q2w3e',
    authDomain: 'task-app-1q2w3e.firebaseapp.com',
    storageBucket: 'task-app-1q2w3e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-UigAA_AaUYJ9Oxv85cRBLMfcO7rbz6Y',
    appId: '1:93120238692:android:e61785401792db2aa4bb71',
    messagingSenderId: '93120238692',
    projectId: 'task-app-1q2w3e',
    storageBucket: 'task-app-1q2w3e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPoyrMm-ers3rbVivOlzKW_fiVs7xT39A',
    appId: '1:93120238692:ios:e6e8bd74052daabda4bb71',
    messagingSenderId: '93120238692',
    projectId: 'task-app-1q2w3e',
    storageBucket: 'task-app-1q2w3e.firebasestorage.app',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsj4AL-XM7624dmyBmTLKUqpsZTzUd9Kg',
    appId: '1:93120238692:web:299ad3ec347a1a38a4bb71',
    messagingSenderId: '93120238692',
    projectId: 'task-app-1q2w3e',
    authDomain: 'task-app-1q2w3e.firebaseapp.com',
    storageBucket: 'task-app-1q2w3e.firebasestorage.app',
  );

}